language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_JS=0
    - TASK_TESTS_COVERAGE=0

php:
- 5.5
- 5.6
- 7.0
- 7.1

sudo: false

install:
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
